/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "RPC.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

avg *
rpc_avg_1(input *argp, CLIENT *clnt)
{
	static avg clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_AVG,
		(xdrproc_t) xdr_input, (caddr_t) argp,
		(xdrproc_t) xdr_avg, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

min_max *
rpc_mm_1(input *argp, CLIENT *clnt)
{
	static min_max clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_MM,
		(xdrproc_t) xdr_input, (caddr_t) argp,
		(xdrproc_t) xdr_min_max, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

mult *
rpc_mult_1(input *argp, CLIENT *clnt)
{
	static mult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_MULT,
		(xdrproc_t) xdr_input, (caddr_t) argp,
		(xdrproc_t) xdr_mult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
