/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_avg (XDR *xdrs, avg *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->avgrs))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_min_max (XDR *xdrs, min_max *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->mm.mm_val, (u_int *) &objp->mm.mm_len, 2,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mult (XDR *xdrs, mult *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->mulrs.mulrs_val, (u_int *) &objp->mulrs.mulrs_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
